import { analyzeDataset, stableStringify } from "./audit-engine";
import { runFixedRegressionSuite } from "./regression-suite";
import { sha256Hex } from "./hash";
import type { AuditReport, DatasetMetadata, DatasetRow } from "./types";

function markdownValue(value: string) {
  const cleaned = value
    .trim()
    .replace(/[\r\n]+/gu, " ");
  if (!cleaned) return "Not supplied";

  return [...cleaned].map((character) => {
    const code = character.codePointAt(0) ?? 0;
    const isAsciiPunctuation =
      (code >= 33 && code <= 47) ||
      (code >= 58 && code <= 64) ||
      (code >= 91 && code <= 96) ||
      (code >= 123 && code <= 126);
    return isAsciiPunctuation ? `&#${code};` : character;
  }).join("");
}

function createDataCard(report: Omit<AuditReport, "dataCardMarkdown">) {
  const findingRows = report.findings.length
    ? report.findings
        .map(
          (item) =>
            `| ${item.severity.toUpperCase()} | ${markdownValue(item.title)} | ${item.count} | ${markdownValue(item.remediation)} |`,
        )
        .join("\n")
    : "| PASS | No configured detector raised a finding | 0 | Continue documented review before release. |";

  return `# Data card — ${markdownValue(report.metadata.datasetName || "Unnamed dataset")}

Generated by DataTrust Gate report schema ${report.schemaVersion}.

## Release decision

- **Gate:** ${report.status}
- **Rows:** ${report.summary.rowCount}
- **Columns:** ${report.summary.columnCount}
- **Blocking finding groups:** ${report.summary.blockCount}
- **Warning finding groups:** ${report.summary.warningCount}

## Reproducibility

- **Dataset SHA-256:** \`${report.datasetHash}\`
- **Configuration SHA-256:** \`${report.configurationHash}\`
- **Report SHA-256:** \`${report.reportHash}\`
- **Generated:** ${report.generatedAt}

The report hash excludes the generation timestamp and Markdown rendering so the same bounded rows, metadata, detector version, and fixed regression suite produce the same value.

## Intended use and governance

| Field | Recorded value |
|---|---|
| Purpose | ${markdownValue(report.metadata.purpose)} |
| Provenance | ${markdownValue(report.metadata.provenance)} |
| License / permission basis | ${markdownValue(report.metadata.license)} |
| Label column | ${markdownValue(report.summary.inferredColumns.label ?? "Not detected")} |
| Split column | ${markdownValue(report.summary.inferredColumns.split ?? "Not detected")} |
| Identifier column | ${markdownValue(report.summary.inferredColumns.id ?? "Not detected")} |

Release metadata is authored by the operator. Markdown controls and URL delimiters are encoded so these values render as inert text. Do not place raw dataset values, personal data, or secrets in metadata fields.

## Findings

| Severity | Finding | Count | Recommended action |
|---|---|---:|---|
${findingRows}

Evidence in this card is row-located and masked. Raw cell values are not included.

## Fixed detector regression suite

- **Suite:** ${report.regressionSuite.id} v${report.regressionSuite.suiteVersion}
- **Input artifact SHA-256:** \`${report.regressionSuite.inputArtifactHash}\`
- **Gold artifact SHA-256:** \`${report.regressionSuite.goldArtifactHash}\`
- **Expected findings matched:** ${report.regressionSuite.matchedExpectedFindings}/${report.regressionSuite.expectedFindings}
- **Unexpected / missed findings:** ${report.regressionSuite.unexpectedFindings} / ${report.regressionSuite.missedExpectedFindings}
- **Clean rows flagged:** ${report.regressionSuite.cleanRowsFlagged}/${report.regressionSuite.cleanRows}

${report.regressionSuite.scope}

## Limitations and residual risk

${report.limitations.map((item) => `- ${item}`).join("\n")}

This automated gate supports review; it is not a legal-compliance engine, privacy certification, security certification, or substitute for accountable human approval.
`;
}

export async function createAuditReport(
  rows: DatasetRow[],
  metadata: DatasetMetadata,
): Promise<AuditReport> {
  const analysis = analyzeDataset(rows, metadata);
  const regressionSuite = await runFixedRegressionSuite();
  const datasetHash = await sha256Hex(rows);
  const configurationHash = await sha256Hex({
    schemaVersion: "1.0",
    metadata,
    detector: "data-trust-gate-rules-v1",
  });
  const generatedAt = new Date().toISOString();
  const reportCore = {
    schemaVersion: "1.0" as const,
    status: analysis.status,
    datasetHash,
    configurationHash,
    metadata,
    summary: analysis.summary,
    findings: analysis.findings,
    regressionSuite,
    limitations: [
      "Pattern matching can miss unusual identifier formats and can flag harmless strings that resemble identifiers.",
      "Near-duplicate detection uses token similarity, not semantic equivalence, and its fixed threshold is only a review aid.",
      "Near-duplicate work budgets can leave tokens or candidate pairs unevaluated; consult the comparison and token-limit telemetry before interpreting a zero or partial count.",
      "Split leakage and conflicting-label checks depend on correctly configured identifier, split, and label columns.",
      "Class imbalance is a distribution warning; it does not determine fairness, fitness for purpose, or downstream model quality.",
      "Masking report evidence does not anonymise or transform the uploaded source rows.",
      "The fixed synthetic regression suite confirms maintained examples only and must not be presented as precision, recall, or real-world accuracy.",
    ],
  };
  const reportHash = await sha256Hex(stableStringify(reportCore));
  const withoutCard: Omit<AuditReport, "dataCardMarkdown"> = {
    ...reportCore,
    generatedAt,
    reportHash,
  };
  return {
    ...withoutCard,
    dataCardMarkdown: createDataCard(withoutCard),
  };
}
